/*INDEX CRIADOS*/

CREATE INDEX IND_NOME_AEROPORTO ON 	TB_AEROPORTO(NM_NOME_AEROPORTO);
CREATE INDEX IND_CARGO_FUNCIONARIO ON TB_FUNCIONARIO(ID_CARGO);
CREATE INDEX IND_NM_NOME_COMPANHIA ON TB_COMPANHIA_AEREA(NM_NOME_COMPANHIA);
CREATE INDEX IND_DS_TIPO_CARDAPIO ON TB_SERVICO_PRESTADO(DS_TIPO_CARDAPIO);

/*VISÕES CRIADAS*/
CREATE OR REPLACE VIEW VW_VOOS_BOEINGS (T_DATA_OCORRENCIA,NM_NOME_AEROPORTO_ORIGEM,NM_NOME_AEROPORTO_DESTINO)
	AS
SELECT 
	OCV.DT_DATA_OCORRENCIA,
    AER.NM_NOME_AEROPORTO,
    AER2.NM_NOME_AEROPORTO
FROM 
	TB_OCORRENCIA_VOO OCV
JOIN 
	TB_VOO VOO 
ON
	OCV.ID_VOO = VOO.ID_VOO
JOIN 
	TB_AEROPORTO AER
ON 	
	AER.ID_AEROPORTO = VOO.ID_AEROPORTO_ORIGEM
JOIN 
	TB_AEROPORTO AER2
ON	
	AER2.ID_AEROPORTO = VOO.ID_AEROPORTO_DESTINO	
WHERE OCV.ID_AERONAVE IN 
	(SELECT 
		ID_AERONAVE 
	FROM 
		TB_AERONAVE 
	WHERE 
		NM_MODELO 
	BETWEEN 700 AND 799
    )
AND 
	OCV.DT_DATA_OCORRENCIA  IS NOT NULL
ORDER BY
	OCV.DT_DATA_OCORRENCIA;

/*SEGUNDA VIEW CRIADA*/

CREATE OR REPLACE VIEW VW_VOOS_FEITOS_ATE_AGORA_NESTE_ANO (NM_NOME_AEROPORTO,NM_ESTADO,ID_VOO) AS
SELECT 
	aer.nm_nome_aeroporto,
    enr.nm_estado,
    count(VOO.ID_VOO)
FROM 
	tb_aeroporto AER
JOIN 
	TB_ENDERECO ENR
ON 
	ENR.ID_ENDERECO = AER.ID_ENDERECO
JOIN
	tb_voo VOO
ON 
	VOO.ID_AEROPORTO_ORIGEM = AER.ID_AEROPORTO
JOIN
	tb_ocorrencia_voo ocv
on 
	voo.id_voo = ocv.ID_VOO
WHERE
	OCV.DT_DATA_OCORRENCIA >= (SELECT DATE_ADD(CURDATE(), INTERVAL ((-dayofyear(curdate()))+1) DAY))
    and
    OCV.DT_DATA_OCORRENCIA < CURDATE()
group by 
	NM_NOME_AEROPORTO
ORDER BY ENR.NM_ESTADO;