/* A )JUNÇÃO DE TRÊS OU MAIS TABELAS COM ODER BY*/
-- LISTA DE COMPANHIAS AREAS E A QUANTIDADE DE AEROPOROS EM QUE OPERA
SELECT 
	CA.NM_NOME_COMPANHIA as 'Companhia Áerea', 
    count(AER.ID_AEROPORTO) as  'Quantidade de Aeroportos que opera'
FROM 
	tb_companhia_aerea CA 
JOIN tb_operacao_aeroporto_cia_aerea OCIA
ON CA.ID_COMPANHIA_AEREA = OCIA.ID_COMPANHIA_AEREA
JOIN tb_aeroporto AER
ON OCIA.ID_AEROPORTO = AER.ID_AEROPORTO
GROUP BY NM_NOME_COMPANHIA
ORDER BY CA.NM_NOME_COMPANHIA