/* A )JUNÇÃO DE TRÊS OU MAIS TABELAS COM ODER BY*/
-- LISTA DE COMPANHIAS AREAS E A QUANTIDADE DE AEROPOROS EM QUE OPERA
SELECT 
	CA.NM_NOME_COMPANHIA as 'Companhia Áerea', 
    count(AER.ID_AEROPORTO) as  'Quantidade de Aeroportos que opera'
FROM 
	tb_companhia_aerea CA 
JOIN 
    tb_operacao_aeroporto_cia_aerea OCIA
ON 
    CA.ID_COMPANHIA_AEREA = OCIA.ID_COMPANHIA_AEREA
JOIN
     tb_aeroporto AER
ON OCIA.ID_AEROPORTO = AER.ID_AEROPORTO
GROUP BY
     NM_NOME_COMPANHIA
ORDER BY
     CA.NM_NOME_COMPANHIA
/*C) */
/*AEROROTOS QUE MAIS RECEBEM VOOS*/
SELECT 
	AER.NM_NOME_AEROPORTO 'NOME DO AEROPORTO',
    ENR.NM_CIDADE 'CIDADE DO AEROPORTO',
	COUNT(VOO.ID_VOO) 'NÚMERO DE VOOS'
FROM 
	TB_AEROPORTO AS AER
JOIN 
	TB_ENDERECO ENR
ON
	ENR.ID_ENDERECO = AER.ID_ENDERECO
JOIN 
	TB_VOO AS VOO
ON 
	VOO.ID_AEROPORTO_DESTINO = AER.ID_AEROPORTO
WHERE 
	AER.DT_DATA_INAUGURACAO BETWEEN '1990/01/01' AND '1999/01/31'
AND
	AER.NM_NOME_AEROPORTO NOT LIKE '%INTERNACIONAL%'
GROUP BY
	AER.ID_AEROPORTO
ORDER BY 3 DESC;


/*NOME DA COMPHANIA COM A DATA DO PRIMEIRO DE O ULTIMO VOO REALIZADO*/
SELECT 
	CIA.NM_NOME_COMPANHIA 'NOME COMAPHINA AEREA ',
    MIN(OCV.DT_DATA_OCORRENCIA) 'DATA DO PRIMEIRO VOO REALIZADO',
    MAX(OCV.DT_DATA_OCORRENCIA)  'DATA D OULTIMO VOO REALIZADO'
FROM 
	tb_companhia_aerea CIA
JOIN 
	TB_VOO VOO
ON 
	CIA.ID_COMPANHIA_AEREA = VOO.ID_COMPANHIA_AEREA
JOIN 
	tb_ocorrencia_voo OCV
ON 
    OCV.ID_VOO = VOO.ID_VOO
GROUP BY  
    CIA.NM_NOME_COMPANHIA;